### ISSUE TITLE
Inclusions endpoint is broken

### ISSUE THREAD

**Issue by esperancaJS** [altario/venga-bugs#3]
Requests like:

```
GET http://apivenga.altar.io/v1/inclusions?search=Wel
```

return 500

Here's the documentation:
https://peaceful-tor-60103.herokuapp.com/#api-Inclusion-GetInclusions

**Comment by JonnyBGod** [comment]
this should be used like:

```
https://apivenga.altar.io/v1/inclusions?search= {"query": "Wel" }
```

**Comment by JonnyBGod** [comment]
better yet, the url should be encoded:

```
https://apivenga.altar.io/v1/inclusions?search%3D%7B%22query%22%3A%22Wel%22%7D
```

**Comment by esperancaJS** [comment]
still not working :s

**Comment by JonnyBGod** [comment]
https://apivenga.altar.io/v1/inclusions?search={%22query%22:%22Wel%22}

```
[{"name":"Welcome drink"}]
```

This is working.

**Comment by JonnyBGod** [comment]
https://apivenga.altar.io/v1/inclusions?search={"query":"Wel"}

This also works

**Comment by esperancaJS** [comment]
got it to work!
had to put the term inside an array and stringify it.
The request ended up like: `http://apivenga.altar.io/v1/inclusions?search=%7B%22query%22:%22%5B%5C%22wel%5C%22%5D%22%7D`

**Comment by JonnyBGod** [comment]
That is not working you are receiving all inclusions. Not filtering.

**Comment by esperancaJS** [comment]
got it!
`http://apivenga.altar.io/v1/inclusions?search={%22query%22:%22we%22}`
